.TH "CUTEMAZE" "6" "February 2014"

.SH "NAME"
cutemaze \- top\-down maze game

.SH "SYNOPSIS"
.PP
.B cutemaze

.SH "DESCRIPTION"
.PP
CuteMaze is a simple, top-down game in which mazes are randomly generated
using one of a choice of several different algorithms. You move the character
through the maze while hunting for targets (cheese, by default)--the game is
won once all of these targets have been picked up.

.SH "COPYRIGHT"
.PP
Copyright \(co 2014 Graeme Gott
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

.SH "AUTHOR"
.PP
Graeme Gott <graeme@gottcode.org>.
